### ISSUE TITLE
Short-circuit capability on non-existence

### ISSUE THREAD

**Issue by moogleberry** [getgauge/taiko#1001]
### Expected behavior
A flag on `exists()`, or new function that detects existence, but short-circuits on non-existence.

The lack of this capability makes many non-existence checks run into timeout errors, and require manual timeout settings to shorten, leading to inflexible and error prone tests due to over-shortening.

### Actual behavior
The `exists()` function short-circuits its waiting period when existence of a selected element is found to be true.  This is optimal when existence is desired.  There is no way to short-circuit the waiting period when non-existence of an element is desired, such as waiting for certain text, animation, modal to disappear.

### Steps to reproduce
1. openBrowser()
2. goto("https://taiko.gauge.org/#/")
Observe the difference between the following:
3. waitFor(async() => (await text("Reliable browser automation").exists()))
And
4. waitFor(async() => !(await text("Reliable browser automation").exists()))
Observe that in 3, the text is immediately found to exist and the function returns, but in 4, the entire timeout must finish before returning because existence is considered the desired condition.  

### Versions
```
1.0.3
```

**Comment by zabil** [comment]
This piece of code 

```
waitFor(async() => !(await text("Reliable browser automation").exists()))
```

Keeps running the condition `async() => !(await text("Reliable browser automation").exists())` until it returns `true` or times out. In this case `!(await text("Reliable browser automation").exists())` will always return `false` as `await text("Reliable browser automation").exists()`  returns `true` because the element is always available on the screen.  

> such as waiting for certain text, animation, modal to disappear.

Technically you *can* short circuit it as follows 

```
waitFor(async() => !(await text("Reliable browser automation").exists(0, 0)))
```

`text("Reliable browser automation").exists(0, 0)` does not wait for the element. This won't work on `taiko.gauge.org` but if `Reliable browser automation` were to disappear from the screen it should return `!false` and then exit.

Also, Precede this with a check. For example

```
await text("Modal").exists();
waitFor(async() => !(await text("Modal").exists(0, 0)))
```

Not very readable, but this should work. 

I can't think of a way of introducing another API to make it readable. Ideas are welcome.

**Comment by moogleberry** [comment]
Thank you for the ideas.

What I ended up doing was effectively making my own:
```
const waitForNonexistence = async (element, retryInterval, retryTimeout) => {
  var exists = await element.exists(0, 0);
  var defaultConfig = getConfig(); // added to taiko.js as return defaultConfig
  var ri = defaultConfig.retryInteval;
  var rt = defaultConfig.retryTimeout;

  if(rt <= 0) {
    //timeout met; resolve status
    return await !(exists); 
  } else if(exists) {
    //exists now; wait for nonexistence or timeout
    if(rt && ri) {
      wait(ri) // wait definition from helper.js
      .then(function() { 
        waitForNonexistence(element, ri, rt-ri);
      });
    } else {
      throw new Error("timeout not available");
    }
  } else {
    // does not exist now; short-circuit to resolution
    return true;
  }
}
```

NB: this would work great with a `getConfig()` provided, but can work without it by manually setting the interval/timeout, or by adding your own to `taiko.js`

**Comment by zabil** [comment]
Refer https://github.com/getgauge/taiko/issues/1023
