### ISSUE TITLE
Taiko with proxy

### ISSUE THREAD

**Issue by brandonrock919** [getgauge/taiko#1230]
There is any option to use taiko with authenticated proxy (user:pswd@host:port) ?
example from puppeteer - 
```
const browser = await puppeteer.launch({args: ['--proxy-server=zproxy.lum-superproxy.io:22225'] });
    await page.authenticate({
        username: 'lum-customer-USERNAME-zone-YOURZONE',
        password: 'PASSWORD'
    });
```

**Comment by sriv** [comment]
taiko works similar to puppeteer in this regard. You can pass `--proxy-server=<..>` to taiko's `openBrowser` as an arg. 

Please see the reference for [`openBrowser`](https://docs.taiko.dev/#openbrowser) for available options.

In this case, something like `await openBrowser({args:["--proxy-server=localhost:8080"]});`

As for `page.authenticate`, taiko does not have an API, but here's an example that can perhaps help: https://github.com/getgauge/taiko/blob/master/examples/06-basic-auth.js#L9

**Comment by klhex** [comment]
I think page.authenticate from the puppeteer example indeed relates to the proxy authentication while the example of https://github.com/getgauge/taiko/blob/master/examples/06-basic-auth.js#L9 relates to the basic authentication of a website, which are two different things (for me at least it didn't work as implied above).

A solution that works well with taiko and chromium is to separately install a local proxy server which forwards all traffic to the actual proxy server (e.g. the one of your company). You then make taiko/chromium point to the local proxy which does not require authentication which in turn forwards all traffic to the actual proxy that requires authentication. The auth credentials are entered in the configuration of the local proxy. Example with mitmproxy: https://stackoverflow.com/questions/46002582/chrome-in-headless-mode-provide-credentials-auth-for-proxy

**Comment by ckcr4lyf** [comment]
To add on to @klhex's great solution of using mitmproxy to host a local passwordless proxy with an upstream to the authenticated proxy, if you need to do this in a CI script or something then you can run it in the background via screen.

Furthermore, by default mitmproxy tries to intercept TLS with its own CA. Since we're trying to just use it to proxy to an upstream, this can be problematic since you may get SSL errors in your client application.

This can be avoided by using `--allow-hosts` with some dummy URL, and then mitmproxy will let all other URLs go through untouched.

```
screen -d -m mitmproxy -p 9999 --mode upstream:http://authenticate.proxy.com --upstream-auth username:password --allow-hosts www.dummy.com
```
