### ISSUE TITLE
Ship Taiko with self-signed cert

### ISSUE THREAD

**Issue by scottdavis99** [getgauge/taiko#1260]
Every time Taiko invokes the included Chromium, an "accept/deny incoming network requests" dialog appears on MacOS. If Taiko includes a self-signed certificate, the end user can "accept" the cert and suppress the dialog.

### Manual steps to suppress permissions dialog box on MacOS
To disable permissions dialog box for Chromium installed with Taiko:

https://github.com/puppeteer/puppeteer/issues/4752

Keychain Access > Certificate Assistant > Create a Certificate

Name: TaikoChromium
Identity Type: Self Signed Root
Certificate Type: Code Signing

Click "Create"

Drag cert from "login" to "System"

sudo codesign -s TaikoChromium -f /Users/scott/.nvm/versions/node/v12.14.1/lib/node_modules/
taiko/.local-chromium/mac-724157/chrome-mac/Chromium.app --deep

### Versions
```
Version: 1.0.9 (Chromium:83.0.4103.0)
```

**Comment by dennismphil** [comment]
Thanks for writing out the instructions. 

I had a little trouble finding the Certificate Assistant. Adding a screenshot for bit more clarity for future readers.

![](https://user-images.githubusercontent.com/4141366/82072907-46c39780-968d-11ea-84ee-95df0d39308e.png)

**Comment by sriv** [comment]
I believe this would have to be done manually, since taiko cannot `codesign` chromium binaries.

**Comment by zabil** [comment]
The pop up appears because Taiko launches chromium in debug mode so that it can communicate via CDP.

As this is an OS related security feature, we should not be getting around it by self signing chromium binaries. The binaries should be signed either at source (google) or the user must be aware that a port is open to explicitly grant the permission or overriding it using instructions mentioned above.
