### ISSUE TITLE
confirm() with an unknown message

### ISSUE THREAD

**Issue by pbanyard** [getgauge/taiko#1293]
Currently there is no way of using confirm() if I don't know what the message will be.
confirm('Message', async () => await accept())
await click('Show Confirm')
I have a pop up that includes a date in the message e.g. "Are you sure you want to put this on Hold till Wed, 10/06/2020?".
The Date part of the message will change based on the day the task is run so how can I arm the confirm handler if I don't know what the message will be in advance?
In some scenarios I could work out what the message but the code in the step would be more reusable if I didn't have to.

### Expected behavior
Would like to be able to use confirm() with either partial or unknown message

### Actual behavior
Not currently possible

### Steps to reproduce
1. Create a pop up with some run time created text e.g. a date
2. confirm('Message', async () => await accept()) - the 'Message' is not fully known at coding time

### Versions
```
npm 6.13.4
taiko 1.0.11
```

**Comment by sriv** [comment]
Currently taiko expects the exact message, but this seems like a legitimate use case.

**Comment by BugDiver** [comment]
@pbanyard As discussed with the team we are going to enhance the `confirm` API to handle these scenarios. We have discussed adding the following enhancements according to the situation

* User know the message
    In this case, the user can use the message to add a handler (the current behavior)

* User know only part of the message
   In this case user can privde a regex which will match the message
  Example: 
   ```js
   await confirm(/Please enter your/, () => await accept("John Wick"));
   ```

* User does not know anything about the message
   In this case user can pass a handler directly, and taiko will pass the message to the callback, so that user can process it inside the callback.


   Example: 
   ```js
   await confirm((message) => {
      if (message === "Please enter your name") {
         await accept("Lucifer");
      } else{
         await dismiss();
      }
   });
   ```
