### ISSUE TITLE
✘ Error: Element focused is not writable

### ISSUE THREAD

**Issue by 1160545** [getgauge/taiko#1308]
i am getting this error when i am trying to write in text field .

Taiko: Version: 1.0.11 (Chromium:84.0.4143.0)

**Comment by NivedhaSenthil** [comment]
Please fill in the issue template so that we can address this issue better @1160545

**Comment by zabil** [comment]
Closing this for now as @1160545 is repeatedly raising issues without filling the template properly.  In order to save time of anyone who might look into this issue I am closing this. Will reopen after clear steps to replicate this issue is available. Also as the message indicates this is a problem with the web app being tested. Please ask this question at the forums https://spectrum.chat/taiko?tab=posts
