### ISSUE TITLE
Taiko is not able to find elements in Angular framework

### ISSUE THREAD

**Issue by raviprasanthgit** [getgauge/taiko#1337]
Taiko is not able to find elements in Angular framework .
  
### Expected behavior
The code should be executed without any error

### Actual behavior
Getting error 'element focused is not writable'

### Steps to reproduce
1. open browser
2. goto url
3. write("Add task");

  ```
        await openBrowser();
        await goto('http://todomvc.com/examples/angularjs/#/');
        await write("Add task");
        await press("Enter");
        assert.ok(await text('1 item left').exists());
```

### Versions
Taiko Version  : 1.0.9   

Note : 
The same code is working in taiko 0.8.0 version

**Comment by NivedhaSenthil** [comment]
This seems to be happening because auto focus is not happening for angular todo site with the version of chromium bundled currently, whereas autofocus happens with the older version of chromium bundled with 0.8.0.  
Reference issue https://bugs.chromium.org/p/chromium/issues/detail?id=1046357
Could be sites behaviour to autofocus for the react sample dint take a deeper look.

**Comment by raviprasanthgit** [comment]
Yeah could be the possible case . On inspecting the element and clicking the element using xpath is bringing the element in focus .

**Comment by NivedhaSenthil** [comment]
Closing this issue as it is the behaviour of browser.
