### ISSUE TITLE
Able to execute a script in normal mode but same script doesn't work in headless mode

### ISSUE THREAD

**Issue by amitsarkar007** [getgauge/taiko#1338]
### Expected behavior
Script should run in headless mode

### Actual behavior
Script doesn't run in headless mode

### Steps to reproduce
1. Execute the script [Taiko-CompareTheMarket](https://github.com/amitsarkar007/Taiko-Scripts/blob/master/Taiko-CompareTheMarket.js)
2. Wait for script execution to finish
3. Execute the script [Taiko-CompareTheMarket-Headless](https://github.com/amitsarkar007/Taiko-Scripts/blob/master/Taiko-CompareTheMarket-Headless.js)

### Code execution
```
PS C:\Users\Neo\OneDrive\Taiko-Scripts> taiko .\Taiko-CompareTheMarket-Headless.js
[PASS] Browser opened
[PASS] Navigated to URL https://www.comparethemarket.com/
[PASS] Clicked element matching text "Car insurance" 1 times
Error: Text field To right of Then please enter it here to get started: not found
    at findElements (C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\lib\elementSearch.js:185:11)
    at async module.exports.write (C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\lib\taiko.js:1519:40)
    at async module.exports.<computed> (C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\lib\taiko.js:3522:14)
    at async global.<computed> (C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\bin\runFile.js:38:15)
    at async C:\Users\Neo\OneDrive\Taiko-Scripts\Taiko-CompareTheMarket-Headless.js:14:9
[PASS] Browser closed
```

### Versions
```
node --version
v12.17.0

taiko --version
Version: 1.0.12 (Chromium: 81.0.3994.0) RELEASE
```

### Note
Default browser changed to Chrome using TAIKO_BROWSER_PATH environment variable

**Comment by zabil** [comment]
Thanks for posting these scripts, it makes so very easy to debug the problem. I added a call to the `screenshot` API in headless mode.

![Screenshot-1593419525690](https://user-images.githubusercontent.com/54427/85991813-df1e9d00-b9eb-11ea-9878-5d77f8d63b01.png)

The site is adding a captcha screen on headless mode. Unfortunately there is no way around this :(  because captchas are good at detecting bots.

I am closing this issue as there is no fix for it. In a testing environment there will be more control to prevent the captcha from showing up.
