### ISSUE TITLE
friendly upload and download API

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1687]
https://docs.taiko.dev/file_upload_and_download/
It is so ugly code
why not design API like these：
upload(fileField(selector),fileName,selector for upload button )
download(selector ,fileName)
fileName can include path

**Comment by roughsoft** [comment]
https://tagui.readthedocs.io/en/latest/index.html
download https://admin.typeform.com/xxx to report.csv

**Comment by zabil** [comment]
@roughsoft really appreciate it if you can fill up the issue template so that someone who wants to pick up this issue has a clear idea. The issue template lists these sections which is missing in this issue. I see them populated when I create a new issue. 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

Please raise issues in these sections for the benefit of readability. Will re-open the issue after all these sections are filled.
