### ISSUE TITLE
Cannot hover to display tooltip

### ISSUE THREAD

**Issue by quynhlev** [getgauge/taiko#1849]
**Describe the bug**
I need to click a tooltip which is displayed when hover to text.
When run No HEADLESS, I must move mouse to hover text then tooltip appears, I can process with tooltip later.
But when I run HEADLESS, it's failed at step to take action on tooltip, I open screenshot report and see tooltip cannot appear

**To Reproduce**
Steps (or script) to reproduce the behavior:

```
hover($("//*[@id='thread-comment-tooltip']//div[text()='Hello']")) 
click($("//*[@class='rc-tooltip-inner']//button[3]"))
```

**Expected behavior**
Can display tooltip and click button on it

**Versions:**
 - Taiko: 1.0.16
 - Mac OS 10.14.6
 - Node.js v12.16.1
 - Gauge v1.0.7

**Comment by NivedhaSenthil** [comment]
Please share a sample html to replicate this

**Comment by levietquynh** [comment]
@NivedhaSenthil you can see my repo here https://github.com/levietquynh/tk_support
When hover to comment "hello", a tooltip will appear. Taiko can pass the hover action, but the tooltip no longer displays, so it'll be failed to find Delete icon.

* Hover to "hello"
* Click to Delete icon
* Click Delete button

**Comment by NivedhaSenthil** [comment]
Hi @quynhlev, sorry for coming back late, just gotta chance to look at the sample. Seems there have been some changes in the app, it currently fails for me at `Enter <value> to Comment input` since the textBox is not found. But going through the flow it feel like when we try to hover and perform action the focus from the element is lost and it couldn't find the element. 
please try doing a `focus` instead, that might help in your case.
