### ISSUE TITLE
Click (& other actions) should fail if it triggers a failed navigation to another page

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#207]
**Expected Behaviour**
Click and other actions can optionally trigger a navigation to another page. If that page fails to load, The action should also fail. The HTTP status code should also be printed.

**Actual Behaviour**
Click and other actions can optionally trigger a navigation to another page. If that page fails to load, the action is still successful.

*Related to #201*

**Comment by NivedhaSenthil** [comment]
As discussed with team, In case of failing `goto` on navigation failure ( #201 ) is valid as the action itself has failed. But in case of `click` or any other action though the actual action is performed successfully failing for navigation failure is like failing for events triggered by the action, in which case we should be actually notifying user about any event failure instead of just navigation failure (which is not pretty straight forward technically though).
Thoughts why we are focusing only on navigation failures ?

**Comment by sriv** [comment]
To add to @NivedhaSenthil - `click` can trigger events such as bring up a popup, which does not cause a navigation. Is it worth bubbling up chained events' errors? 

Somehow I feel, the `click` (and other actions) need not look at events triggered subsequently.

**Comment by zabil** [comment]
For now it is ok for click to just report on it's result. Any failures related to the wrong navigation results should be caught by assertions instead.
