### ISSUE TITLE
Simplest recorder( like Selenium IDE) support [feature request]

### ISSUE THREAD

**Issue by senpl** [getgauge/taiko#214]
Currently there are plenty of selenium IDE recorders.
It would be nice to have option to record with some recorer (for example Selenium IDE) and then export created script into taiko format.

**Comment by shubhamsc** [comment]
@senpl Currently, we don't have any plan to add a recorder in Taiko like Selenium.

**Comment by shubhamsc** [comment]
@senpl We don't have any plans to integrate with a recorder, because we feel the generated code is not very maintainable. if you have any ideas on how to integrate with a recorder, please add your thoughts.

**Comment by senpl** [comment]
I thought that basic actions like clicks on elements could be recorder fast in Selenium IDE. But then converting into taiko format is a waste of time. I guess export option to taiko format from selenium IDE would be simplest solution. But also regex that change Selenium code into taiko code would be fast and to many efficient enough. This option is especially important on pages with lot of inputs, where manually inserting every input would be slow.

**Comment by nehashri** [comment]
@senpl We don't have plans to support any kind of recorder for Taiko. We hope that people will use the repl feature in Taiko to record their tests.
This comes mainly because we believe that the code generated by a recorder is often not readable and hence maintaining test become harder. 
Also, using a recorder will mean working on dom element ids and css xpaths. These can keep changing during the development of websites. We have seen that the change in id/css xpaths are often are the reason for a lot of tests to become flaky or break.

With Taiko we hope to provide a way for tests to be less flaky and help teams build maintainable test suites that they can rely on. I hope this answers your question on our reasons for choosing a repl approach instead of a recorder approach.
