### ISSUE TITLE
Should be able to perform a flow that I am able to perform in chrome

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#303]
**Expected behavior**
If I am able to access the page in IFrame in chrome browser, I should be able to access it using taiko

**Actual behavior**
The page does not load

**Steps to replicate**
* Create html file
```
<!DOCTYPE html>
<html>
<body>

<iframe src="https://waffle.io/" width="750" height="750">
</iframe>

</body>
</html>
```
* Run the following script
```
const { openBrowser, $, click, text, goto } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("file:///.../newFile.html");
        await click($(".icon-bar"));
        await click(text("Sign up"));
        await click("Public Repos");
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
> Getting a blank screen
> The same steps in chrome work fine

**Version**
```
commit - 7cbcce85576988d14d166ff7bb153622ab58586a
```

> Blocks 107

**Comment by NivedhaSenthil** [comment]
It is failing because of 
`Refused to display 'https://github.com/login?client_id=b68f04bdff231220a275&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3Db68f04bdff231220a275%26redirect_uri%3Dhttps%253A%252F%252Fwaffle.io%252Fgithub-callback%26response_type%3Dcode%26scope%3Dpublic_repo%252Cread%253Aorg%252Cuser%253Aemail%26state%3DaWr6xprqmK5WklmSKpBP35E7' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

The same does not work on chrome when loaded inside iFrame. It happens because of github's Content Security Policy (Some [reference](https://stackoverflow.com/questions/38535491/trying-to-render-i-frame-ancestor-violates-the-following-content-security-polic/38750150)) .  Not related to Taiko.

**Comment by sguptatw** [comment]
It works as expected when rendered in an IFrame inside chrome. However not in chromium.
<img width="983" alt="screen shot 2018-12-24 at 10 34 54 am" src="https://user-images.githubusercontent.com/6310197/50391229-98514680-0767-11e9-9988-11ee730148c1.png">

**Comment by NivedhaSenthil** [comment]
Try in incognito. It loads this as the session already exists.
