### ISSUE TITLE
Error: Could not compute box model., run `.trace` for more info.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#307]
**Expected behavior**
Should be able to double click an element

**Actual behavior**
Error: Could not compute box model., run `.trace` for more info.

**Steps to replicate**
* Unzip [html-report.zip](https://github.com/getgauge/taiko/files/2670705/html-report.zip)
* Run the following on REPL
```
> openBrowser()
 ✔ Browser opened
> goto("file:///Users/sswaroop/Downloads/html-report/index.html")
 ✔ Navigated to url "file:///.../html-report/index.html"
> doubleClick("Failed")
 ✘ Error: Could not compute box model., run `.trace` for more info.
```
**Version**
commit - c184a28f73a14c8bfd25a9c9f3e319c0c3b23a02

> Blocks #107

**Comment by sguptatw** [comment]
The same happens when rightClick(<text>) is used

```
> openBrowser()
 ✔ Browser opened
> goto("file:///Users/sswaroop/Downloads/html-report/index.html")
 ✔ Navigated to url "file:///Users/sswaroop/Downloads/html-report/index.html"
> rightClick(text("Failed"))
 ✘ Error: Could not compute box model., run `.trace` for more info.
```

**Comment by NivedhaSenthil** [comment]
This was happening because the element with text "Failed" was hidden and the condition to filter hidden elements did not handle `offsetParent` being `undefined` only `null` case was checked and thus CDP couldn't compute bounding box. `Failed` in the table heading is actually css content and not text (in css `content: "Failed"`).

Fix for filtering `offsetParent undefined` is done in  
cfa47de
