### ISSUE TITLE
Scroll Up/Down of an iframe should scroll the element

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#313]
**Expected behavior**
Scroll Up/Down of an iframe should scroll the element

**Actual behavior**
Scroll Up/Down of an iframe does not scroll the element

**Steps to replicate**
* Create a html file
```
<html>

   <head>
      <title>HTML Iframes</title>
   </head>
	
   <body>
      <p>Document content goes here...</p>
      
      <iframe src = "https://gauge.org/index.html" width = "250" height = "500">
      </iframe>
      
   </body>
	
</html>
```
* Open the REPL
```
> openBrowser()
 ✔ Browser opened
> goto("file:///.../newFile.html")
 ✔ Navigated to url "file:///.../newFile.html"
> scrollUp($("iframe"),200)
 ✔ Scrolled up custom selector $(iframe) by 200 pixels
> scrollDown($("iframe"),200)
 ✔ Scrolled down custom selector $(iframe) by 200 pixels
```
> The events are shown as successful but the IFrame is not scrolled

**Version**
```
commit - 710fd73ca65d97a2bbc4d7ffb9b12de74ddf177b
```
> Blocks #107

**Comment by NivedhaSenthil** [comment]
This is happening because of `VM293:1 Uncaught DOMException: Blocked a frame with origin "http://localhost:5000" from accessing a cross-origin frame.
    at <anonymous>:1:26`.  
Some [reference](https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame)
Handled the exception in d9bed8b
