### ISSUE TITLE
Capture console error

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#322]
Is it possible for taiko to capture console error, this is quite useful in debugging failures

Puppeteer implementation:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('console', msg => console.log('PAGE LOG:', msg.text));
  page.on('pageerror', error => {
    console.log(error.message);
   });
  page.on('response', response => {
    console.log(response.status, response.url);
  });
  page.on('requestfailed', request => {
    console.log(request.failure().errorText, request.url);
  });
  await page.goto('http://somesitethathasconsoleerror');
  await page.waitFor(5000);
  await browser.close();
})();
```

**Comment by negiDharmendra** [comment]
Few questions.

- Should taiko write all error message (or any message ) logged into the browser console to a file?
- What kind of error we expect taiko to log to a file.

       Right now there are only two types of errors which I can think of. 
       1: Page load error
       2: Javascript execution error. 


> > Will it be helpful if the events are emitted from taiko or config to log error messages?
> 
> yes, it will be a great addition

What would be the use case of listening to those error events?

**Comment by saikrishna321** [comment]
@negiDharmendra I have got this implemented under taiko-diagnostics

https://github.com/saikrishna321/taiko-diagnostics#logconsoleinfo-command

**Comment by negiDharmendra** [comment]
I think it should be a part of the **Taiko**.

**Comment by saikrishna321** [comment]
> I think it should be a part of the **Taiko**.

I will create a PR on this. Will deprecate it in taiko-diagnostics and move to taiko. Please take a look at the implementation in taiko-diagnostics and any feedbacks I can work on the PR.

**Comment by negiDharmendra** [comment]
@saikrishna321 We had a discussion about log capturing being part of taiko-diagnostics. All of us agreed on the point keeping it as part of the taiko-diagnostics.

**Comment by negiDharmendra** [comment]
We would like to make some changes on top of the existing API. 

1. Add support for capturing logs from [Runtime.exceptionThrown
](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#event-exceptionThrown)

2. Use [Runtime.consoleAPICalled](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#event-consoleAPICalled) instead of [Console](https://chromedevtools.github.io/devtools-protocol/tot/Console) API as Console API is deprecated.

**Comment by negiDharmendra** [comment]
Few more changes.

- The current implementation prints the entire JSON object which is too much noise to look at. 
- I would say that just print enough information to indicate the failure (The way we see on the browser console) and emit some custom events. User can subscribe to those custom events if they want to.

**Comment by negiDharmendra** [comment]
This feature will be implemented in [taiko-diagnostics](https://github.com/saikrishna321/taiko-diagnostics)

- [Add support for capturing logs from Runtime.exceptionThrown](https://github.com/saikrishna321/taiko-diagnostics/issues/16)
- [Use Runtime.consoleAPICalled instead of Console API](https://github.com/saikrishna321/taiko-diagnostics/issues/17)
- [Printing entire JSON object on STDOUT creates too much noise.](https://github.com/saikrishna321/taiko-diagnostics/issues/18)
