### ISSUE TITLE
Cookie Handling

### ISSUE THREAD

**Issue by SrinivasanTarget** [getgauge/taiko#349]
Setting and deleting a cookie via APIs

**Comment by saikrishna321** [comment]
@SrinivasanTarget https://github.com/getgauge/taiko/blob/0a6fb22b60e769de56c6327110109d000718cb27/lib/taiko.js#L406 
We can only set one cookie, this approach does not work for setting multiple cookies to the same domain/URL.

**Comment by SrinivasanTarget** [comment]
yes CRI exposes API's for those too. I'm planning to improve even the existing cookie handling once this [PR](https://github.com/getgauge/taiko/pull/354) is in.

**Comment by nehashri** [comment]
Adding a new API to set multiple cookies makes the API complex. In favour of simplicity of the API's, we have decided not to implement a API to set multiple cookies at once.

**Comment by saikrishna321** [comment]
@nehashri Are you saying we can extend the existing API to accept multiple cookies?

**Comment by nehashri** [comment]
@saikrishna321 No, We had a small discussion and we decided that we will not extend the api or create new ones to support setting multiple cookies at once. This is mainly because, we didn't want to complicate the api or introduce new ones.
The user should be able to use the setCookie api to do this.
