### ISSUE TITLE
Unable to click a link of Integer.Error message is displayed.

### ISSUE THREAD

**Issue by Prakash0989** [getgauge/taiko#397]
Issue: I am unable to click a link of Integer .Below error message is displayed 
“Error: Invalid parameters (nodeId: integer value expected), run `.trace` for more info.”

Please refer attached screenshot.

### Expected behavior
Should be able to click a link of integers

### Actual behavior
Error message is displayed on clicking a link of integers.

### Steps to reproduce
1. OpenBrowser()
2. goto("url",{timeout:60000})
3. Login into valid credentials
4. click('1000021242')   (Its a link)

### Versions
```
Paste `node` and `taiko
<img width="804" alt="screen shot 2019-02-12 at 12 52 55 pm" src="https://user-images.githubusercontent.com/45254050/52619096-d09f1680-2ec6-11e9-853b-8b839c72fa5d.png">
` versions here.
```

**Comment by NivedhaSenthil** [comment]
Could replicate the issue. As a work around try `await click(link('1000021242'))`

**Comment by suleytron** [comment]
Hey @NivedhaSenthil So I **can't** select with `click(link('1000021242'))`
There is a dynamically generated table where these links are created alongside a product name. With `n` number of rows.

Each link is basically a `span.menulink` and assigned by the system to a number. The workaround I have employed for now is `click($('span.menulink'))` . This only works for selecting the top link in the table. Is there a way to select different ones on a page in an array style selector e.g `click($('span.menulink')[2])`?

Ideally, we need to get to a situation where we can say 
`click(link("x", toLeftOf("productName"))` Because we won't necessarily know the number of the link, just the name of the productName.

**Comment by saikrishna321** [comment]
@suleytron 

> Is there a way to select different ones on a page in an array style selector e.g `click($('span.menulink')[2])` 

Nope not currently, see this  https://github.com/getgauge/taiko/issues/288 Please upvote if you think its much needed feature.

**Comment by suleytron** [comment]
> Nope not currently, see this #288 Please upvote if you think its much needed feature.


@saikrishna321 I see it being useful for a few reasons:

1. The exact issue we have now when using as a workaround.
2. If you need to count how many elements of same type are on a page to make sure you are interacting with something unique.
3. If you are doing something on a page for example adding another article to a list. you could programmatically count the number `#menulink.count` do said action and then redo `#menulink.count` to see +1 in the count.

This is going off-topic now though so feel free to remove.

**Comment by saikrishna321** [comment]
@Prakash0989 @suleytron i can reproduce the issue: click on number.


```
const { openBrowser, goto, reload, click, closeTab, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('https://docs.gauge.org/latest/execution.html#parallel-execution-using-threads');
        await reload();
        await click('1517');
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();

```

**Comment by NivedhaSenthil** [comment]
Many things discussed here, will try to summarise 

>Is there a way to select different ones on a page in an array style selector e.g `click($('span.menulink')[2])`?

Currently no out of box way, like @saikrishna321 pointed out there an open issue for the same.
But `xpath` selector can always be used to fetch elements by index like `$('(//span[@class='menulink'])[2]')`

>Ideally, we need to get to a situation where we can say
`click(link("x", toLeftOf("productName"))` Because we won't necessarily know the number of the link, just the name of the productName. (the right column)

are you facing any issues using proximity selector currently? above mentioned action should be doable

>* If you need to count how many elements of same type are on a page to make sure you are interacting with something unique.
>* If you are doing something on a page for example adding another article to a list. you could programmatically count the number `#menulink.count` do said action and then redo `#menulink.count` to see +1 in the count.

currently counting can be done using `get`, like `(await  $('span.menulink').get()).length`

Issue with clicking number as text has to be fixed.

**Comment by zabil** [comment]
> But xpath selector can always be used to fetch elements by index like $('(//span[@class='menulink'])[2]')

I prefer this over arrays, it's explicit (possibly faster) and simple.

**Comment by suleytron** [comment]
Thanks for the information here, very useful around the xpath approach.xcv

> are you facing any issues using proximity selector currently? above mentioned action should be doable
@NivedhaSenthil The problem with `click(link("x", toLeftOf("productName"))`for our app is we don't know what 'x' will be ahead of time as it is generated dynamically. 

If you look at the table pasted above the numbers are generated when the new item is defined. So I can't define say `click(link('100028743', toLeftOf('make alcohol test'))). At best I can say click the link or integer value, but with no details.

**Comment by NivedhaSenthil** [comment]
`click(link(toLeftOf("productName"))` should click on the link nearest to the left of "productName"

**Comment by NivedhaSenthil** [comment]
fix available in feb6a17

**Comment by suleytron** [comment]
`Click('integer')`
 value now works for me but there is another issue around 
`click(link(toLeftOf("productName"))`
I will write this up as a new ticket and link it to this one.

**Comment by Debashis9012** [comment]
This issue has been fixed. Tested with the below version

``` feb6a17 ```
