### ISSUE TITLE
Merge cookies apis

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#419]
Currently there are 4 apis for handling cookies, try to merge functionality among them and remove unwanted apis.

**Comment by nehashri** [comment]
There are 4 apis for cookies right now. 
- setCookie
- clearBrowserCookies
- deleteCookies
- getCookies
The deleteCookies can handle clearing all browser cookies if no name is provided. Thus, deprecating `clearBrowserCookies`. However, the `setCookies` and `getCookies` are required and cannot be removed.

**Comment by nehashri** [comment]
Fix available in 2688768

**Comment by nehashri** [comment]
Another issue that was found was
setCookie API was not throwing an error if the cookie was not set successfully. It was giving success message. The above fix handles this case too.

**Comment by Debashis9012** [comment]
As we are deprecating ```clearBrowserCookies``` while using its throwing the below warning message:
```DEPRECATION WARNING: clearBrowserCookies is deprecated. use deleteCookies instead```
Other cookies api are working properly.
If setCookies does not set properly then its throwing the required error message:
Example: ```✘ Error: Atleast URL or Domain needs to be specified for setting cookies, run `.trace` for more info```
Based on the above observation this issue has been validated and found fixed with the commit version:```2688768```
