### ISSUE TITLE
Benchmark tests for Taiko

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#501]
Benchmark Taiko against the following frameworks

* Cypress
* Selenium
* Testcafe

The tests can be written against https://github.com/getgauge-contrib/the-internet-express
Record the time taken for each action and compare it to a similar action for other frameworks.

The benchmark must identify api's slower than other frameworks and fix it to run faster.

**Comment by NivedhaSenthil** [comment]
some thoughts to consider when benchmarking,
- how do we address framework's differential behaviour, like Testcafe uses fixture to navigate to page and it is not counted as part of actual step whereas in Taiko it is an explicit `openBrowser` and `goto` that adds up to the action ?
- how do we measure selectors time which will affect the time taken by actions?(like css/xpath selectors vs proximity selectors) we should consider uniformity across frameworks
- how do we address time taken with different configs ? (like an action with `waitForNavigation` set to False will take lesser time than the one which waits by default which has to be handled using explicit waits in other frameworks)
- can benchmarking be done on scenarios instead of api's to accommodate time taking for loading browser, opening pages, waits to be done between actions etc ?

**Comment by zabil** [comment]
> can benchmarking be done on scenarios instead of api's to accommodate time taking for loading browser, opening pages, waits to be done between actions etc ?

Ideally this should be on scenarios which are a group of actions rather than a single api.

**Comment by NivedhaSenthil** [comment]
there are tests added here https://github.com/getgauge-contrib/Angular-JumpStart/tree/master/benchmarks for flows that tests the sample angular customer manager app for adding, editing, filtering and viewing customer details.
