### ISSUE TITLE
Should be able to click text visible on the screen

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#598]
## Expected behaviour 
Should be able to click text visible on the screen

## Actual behavior
If the Text is value of an inputBox, this action is not successful

## Steps to replicate
* Open the REPL
```
> openBrowser()
 ✔ Browser opened
> goto("https://www.irctc.co.in/nget/train-search")
 ✔ Navigated to url https://www.irctc.co.in/nget/train-search
> write("KSR BENGALURU - SBC",into(textBox({placeholder:"From*"})))
 ✔ Wrote KSR BENGALURU - SBC into the text field[@placeholder = concat('From*', "")]
> press("Enter")
 ✔ Pressed the Enter key
> write("HUBBALLI JN - UBL",into(textBox({placeholder:"To*"})))
 ✔ Wrote HUBBALLI JN - UBL into the text field[@placeholder = concat('To*', "")]
> press("Enter")
 ✔ Pressed the Enter key
> click(<Today's date>)
 ✘ Error: Element with text <Date> not found, run `.trace` for more info.
```
**Note: Today’s date is the default value of the calendar box.

**Version**
```
commit - d4a99381515a3a6262f829eee79a8e00197ada05
```

**Comment by nehashri** [comment]
The example quoted above uses AngularJS. AngularJS uses two way data binding for input elements. AngularJS also defines a directive for the input element that adds extra behavior to the element. The ng-model directive stores/updates the value of the input field into/from a variable.

Because of this, the value is not actually reflected on the input element directly. Hence, taiko fails to read the data.
