### ISSUE TITLE
Add a .api command to list all taiko methods and description

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#7]
Register a command that will list method and documentation of all the available taiko methods.
For e.g.

```
> .api
openBrowser() - Opens a browser
click("element") - Clicks an element with text  "element"
```

Figure out a way to render this from the inline documentation.

**Comment by kashishm** [comment]
`.api` and `.api <function>` is available in the REPL.

**Comment by zabil** [comment]
There's an error while running `.api`

```
browser              Returns the browser insance created using openBrowser.
page                 Returns the page instance.
selector             Identifies an element on the page.
readline.js:1021
            throw err;
            ^

TypeError: Cannot read property 'trim' of undefined
    at map (/home/zabilcm/.g/taiko/repl.js:179:77)
    at Array.map (<anonymous>)
    at d.children.map.c (/home/zabilcm/.g/taiko/repl.js:179:10)
    at Array.map (<anonymous>)
    at desc (/home/zabilcm/.g/taiko/repl.js:178:6)
    at doc.forEach.e (/home/zabilcm/.g/taiko/repl.js:159:27)
    at Array.forEach (<anonymous>)
    at displayUsage (/home/zabilcm/.g/taiko/repl.js:157:9)
    at REPLServer.action (/home/zabilcm/.g/taiko/repl.js:74:18)
    at REPLServer.parseREPLKeyword (repl.js:1062:16)

```

**Comment by sguptatw** [comment]
**Expected behavior**
Should get the list of apis

**Actual behavior**
getting `API usage not available`

**Steps to replicate**
> .\taiko
___________      .__ __             Interactive browser automation.
\__    ___/____  |__|  | ______
  |    |  \__  \ |  |  |/ /  _ \    Version: 0.0.6
  |    |   / __ \|  |    <  <_> )
  |____|  (____  /__|__|_ \____/    Documentation: https://getgauge.github.io/taiko/
               \/        \/         Type .api for help and .exit to quit

> .api
API usage not available.

**Comment by sguptatw** [comment]
Working as expected now
