### ISSUE TITLE
Does taiko has offline installation like Gauge?

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/taiko#795]
Does taiko has offline installation like Gauge?

**Comment by zabil** [comment]
Taiko is a node js library and depends on modules from the npm registry. So the best way to try a local installation is to try it via and offline npm registry.

There are some instructions on local installation of npm modules in this article 
https://addyosmani.com/blog/using-npm-offline/

Unfortunately, because of it's complexity there cannot be a pre-packaged offline installer.
