### ISSUE TITLE
Should be able to select an element based on how it is rendered on UI

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#93]
**Expected behavior**
If an element is rendered on the left of another element, the user should be able to select it using toLeftOf

**Actual behavior**
Getting element not found. However when the script is changed to toRightOf. I am not getting the error.

**Steps to replicate**
* Run the script
```
(async () => {
    try {
        await openBrowser();
        await goto("makemytrip.com");
        await click(inputField({"id":"hp-widget__paxCounter_pot"}));
        await click(link("2",below(contains("ADULTS"))));
        await click(link("1",below(contains("CHILDREN"))));
        await click(link("Premium Economy",above("Done")));
        await click("Done");
        await click(button("Search"));
        await click(link("Book"))
        //MMTPAY
        console.log(await text("MMTPAY").exists())
        
        await click(radioButton(toLeftOf("No, I do not want to insure my trip")))
        await waitFor("5000")
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
**Version**
```
c69ac1f01c1ac25066b806fcbe47d097e675d3c1
Date - Mon Aug 6 09:56:30 2018 +0530
```

**Comment by NivedhaSenthil** [comment]
This happens because the button toLeftOf("No, I do not want to insure my trip") is actually span painted to look like a radiobutton the input field is not visible in UI. When we select toRightOf it picks up some other radio button which is near MMTPAY. 

Something like below works,

`click($('.upsell_radio_icon'),toLeftOf(text("No, I do not want to insure my trip")))`
