### ISSUE TITLE
 running **gauge init js**    unable to initialize a sample Taiko project 

### ISSUE THREAD

**Issue by kimr01** [getgauge/taiko#960]
### Expected behavior
initialize a sample Taiko project 

![Ticket2-Running Gage init js issue](https://user-images.githubusercontent.com/3803389/70432887-29ecbd80-1a78-11ea-97de-dbce716dd4cd.GIF)

### Actual behavior
C:\Users\richa>gauge init js
'gauge' is not recognized as an internal or external command,
operable program or batch file.

### Steps to reproduce
**1.  C:\Users\richa>npm install @getgauge/cli**

Fetching download url for Gauge version 1.0.6
Downloading https://github.com/getgauge/gauge/releases/download/v1.0.6/gauge-1.0.6-windows.x86.zip to ./bin
npm WARN richa No repository field.
npm WARN richa No license field.

+ @getgauge/cli@1.0.6
updated 1 package and audited 113 packages in 23.85s
found 0 vulnerabilities

**2.  run gauge init js** 

![gauge-cmd error](https://user-images.githubusercontent.com/3803389/70432942-4ab51300-1a78-11ea-80ca-de75a4f32529.GIF)

### Versions
```
+ @getgauge/cli@1.0.6
```
### OS
```
Windows 10 x86
```

**Comment by nehashri** [comment]
@kimr01 As the error clearly state, `gauge` command is not found in your PATH. This is because you have installed Gauge in your local node_modules. You need to call `node_modules/@getgauge/cli/bin/gauge init js`(this can be done only from your test project folder) or install Gauge globally. Please look at https://docs.gauge.org/getting_started/installing-gauge.html for ways to install Gauge.
